### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by asubiotto**
@fdhoff

### CODE REVIEW

**Comment by fdhoff** [comment]
Works for me

**Comment by asubiotto** [comment]
Stop merging my shit. just tell me it looks good and I'll do it

**Comment by fdhoff** [comment]
Please add a little more specifics on what it means to stream data to
nanocubes and the purpose

**Comment by asubiotto** [comment]
alright. Do you have any suggestions?

**Comment by fdhoff** [comment]
I already changed the Google doc

**Comment by asubiotto** [comment]
Cool. Let me check it out. Do you want me to hand it in?

**Comment by fdhoff** [comment]
Well we need to present in class tomorrow for a few minutes. Maybe we'll
just show off what we've found out about the source code and a demo of
nanocube..

**Comment by asubiotto** [comment]
I don't think we need to do a demo. Don't we need to hand in our proposal
though? I think just saying what we want to do is enough.

**Comment by fdhoff** [comment]
He said to prepare a 3 min talk.  So I think we should show a demo and say
what we want it to do instead.

**Pull request merged**
